sudo: false
env:
  global:
    - APM_TEST_PACKAGES=""
  matrix:
    - ATOM_CHANNEL=stable
addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
